[package]
name = "layout"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.6"
rand = "0.8"

[dev-dependencies]
svg = "0.13"